// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package db

import (
	"context"

	"ai-zombie-defense/db/types"
)

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (username, email, password_hash) VALUES (?, ?, ?)
`

type CreatePlayerParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreatePlayer(ctx context.Context, db DBTX, arg *CreatePlayerParams) error {
	_, err := db.ExecContext(ctx, createPlayer, arg.Username, arg.Email, arg.PasswordHash)
	return err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE player_id = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, db DBTX, playerID int64) error {
	_, err := db.ExecContext(ctx, deletePlayer, playerID)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT player_id, username, email, password_hash, created_at, last_login_at, is_banned, banned_reason, banned_until FROM players WHERE player_id = ?
`

func (q *Queries) GetPlayer(ctx context.Context, db DBTX, playerID int64) (*Player, error) {
	row := db.QueryRowContext(ctx, getPlayer, playerID)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.IsBanned,
		&i.BannedReason,
		&i.BannedUntil,
	)
	return &i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT player_id, username, email, password_hash, created_at, last_login_at, is_banned, banned_reason, banned_until FROM players WHERE email = ?
`

func (q *Queries) GetPlayerByEmail(ctx context.Context, db DBTX, email string) (*Player, error) {
	row := db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.IsBanned,
		&i.BannedReason,
		&i.BannedUntil,
	)
	return &i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT player_id, username, email, password_hash, created_at, last_login_at, is_banned, banned_reason, banned_until FROM players WHERE username = ?
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, db DBTX, username string) (*Player, error) {
	row := db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.IsBanned,
		&i.BannedReason,
		&i.BannedUntil,
	)
	return &i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT player_id, username, email, password_hash, created_at, last_login_at, is_banned, banned_reason, banned_until FROM players ORDER BY username
`

func (q *Queries) ListPlayers(ctx context.Context, db DBTX) ([]*Player, error) {
	rows, err := db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.PlayerID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.IsBanned,
			&i.BannedReason,
			&i.BannedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerLastLogin = `-- name: UpdatePlayerLastLogin :exec
UPDATE players SET last_login_at = ? WHERE player_id = ?
`

type UpdatePlayerLastLoginParams struct {
	LastLoginAt types.NullTimestamp `json:"last_login_at"`
	PlayerID    int64               `json:"player_id"`
}

func (q *Queries) UpdatePlayerLastLogin(ctx context.Context, db DBTX, arg *UpdatePlayerLastLoginParams) error {
	_, err := db.ExecContext(ctx, updatePlayerLastLogin, arg.LastLoginAt, arg.PlayerID)
	return err
}

const updatePlayerPassword = `-- name: UpdatePlayerPassword :exec
UPDATE players SET password_hash = ? WHERE player_id = ?
`

type UpdatePlayerPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	PlayerID     int64  `json:"player_id"`
}

func (q *Queries) UpdatePlayerPassword(ctx context.Context, db DBTX, arg *UpdatePlayerPasswordParams) error {
	_, err := db.ExecContext(ctx, updatePlayerPassword, arg.PasswordHash, arg.PlayerID)
	return err
}

const updatePlayerProfile = `-- name: UpdatePlayerProfile :exec
UPDATE players SET username = ?, email = ? WHERE player_id = ?
`

type UpdatePlayerProfileParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	PlayerID int64  `json:"player_id"`
}

func (q *Queries) UpdatePlayerProfile(ctx context.Context, db DBTX, arg *UpdatePlayerProfileParams) error {
	_, err := db.ExecContext(ctx, updatePlayerProfile, arg.Username, arg.Email, arg.PlayerID)
	return err
}
