// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_progression.sql

package db

import (
	"context"
)

const addDataCurrency = `-- name: AddDataCurrency :exec
UPDATE player_progression
SET data_currency = data_currency + ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE player_id = ?
`

type AddDataCurrencyParams struct {
	DataCurrency int64 `json:"data_currency"`
	PlayerID     int64 `json:"player_id"`
}

func (q *Queries) AddDataCurrency(ctx context.Context, db DBTX, arg *AddDataCurrencyParams) error {
	_, err := db.ExecContext(ctx, addDataCurrency, arg.DataCurrency, arg.PlayerID)
	return err
}

const createPlayerProgression = `-- name: CreatePlayerProgression :exec
INSERT INTO player_progression (player_id) VALUES (?)
`

func (q *Queries) CreatePlayerProgression(ctx context.Context, db DBTX, playerID int64) error {
	_, err := db.ExecContext(ctx, createPlayerProgression, playerID)
	return err
}

const getPlayerProgression = `-- name: GetPlayerProgression :one
SELECT player_id, level, experience, prestige_level, data_currency, total_matches_played, total_waves_survived, total_kills, total_deaths, total_scrap_earned, total_data_earned, updated_at FROM player_progression WHERE player_id = ?
`

func (q *Queries) GetPlayerProgression(ctx context.Context, db DBTX, playerID int64) (*PlayerProgression, error) {
	row := db.QueryRowContext(ctx, getPlayerProgression, playerID)
	var i PlayerProgression
	err := row.Scan(
		&i.PlayerID,
		&i.Level,
		&i.Experience,
		&i.PrestigeLevel,
		&i.DataCurrency,
		&i.TotalMatchesPlayed,
		&i.TotalWavesSurvived,
		&i.TotalKills,
		&i.TotalDeaths,
		&i.TotalScrapEarned,
		&i.TotalDataEarned,
		&i.UpdatedAt,
	)
	return &i, err
}

const incrementExperience = `-- name: IncrementExperience :exec
UPDATE player_progression
SET experience = experience + ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE player_id = ?
`

type IncrementExperienceParams struct {
	Experience int64 `json:"experience"`
	PlayerID   int64 `json:"player_id"`
}

func (q *Queries) IncrementExperience(ctx context.Context, db DBTX, arg *IncrementExperienceParams) error {
	_, err := db.ExecContext(ctx, incrementExperience, arg.Experience, arg.PlayerID)
	return err
}

const incrementMatchStats = `-- name: IncrementMatchStats :exec
UPDATE player_progression
SET total_matches_played = total_matches_played + ?,
    total_waves_survived = total_waves_survived + ?,
    total_kills = total_kills + ?,
    total_deaths = total_deaths + ?,
    total_scrap_earned = total_scrap_earned + ?,
    total_data_earned = total_data_earned + ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE player_id = ?
`

type IncrementMatchStatsParams struct {
	TotalMatchesPlayed int64 `json:"total_matches_played"`
	TotalWavesSurvived int64 `json:"total_waves_survived"`
	TotalKills         int64 `json:"total_kills"`
	TotalDeaths        int64 `json:"total_deaths"`
	TotalScrapEarned   int64 `json:"total_scrap_earned"`
	TotalDataEarned    int64 `json:"total_data_earned"`
	PlayerID           int64 `json:"player_id"`
}

func (q *Queries) IncrementMatchStats(ctx context.Context, db DBTX, arg *IncrementMatchStatsParams) error {
	_, err := db.ExecContext(ctx, incrementMatchStats,
		arg.TotalMatchesPlayed,
		arg.TotalWavesSurvived,
		arg.TotalKills,
		arg.TotalDeaths,
		arg.TotalScrapEarned,
		arg.TotalDataEarned,
		arg.PlayerID,
	)
	return err
}

const updateLevel = `-- name: UpdateLevel :exec
UPDATE player_progression
SET level = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE player_id = ?
`

type UpdateLevelParams struct {
	Level    int64 `json:"level"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) UpdateLevel(ctx context.Context, db DBTX, arg *UpdateLevelParams) error {
	_, err := db.ExecContext(ctx, updateLevel, arg.Level, arg.PlayerID)
	return err
}

const updatePlayerProgression = `-- name: UpdatePlayerProgression :exec
UPDATE player_progression
SET level = ?,
    experience = ?,
    prestige_level = ?,
    data_currency = ?,
    total_matches_played = ?,
    total_waves_survived = ?,
    total_kills = ?,
    total_deaths = ?,
    total_scrap_earned = ?,
    total_data_earned = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE player_id = ?
`

type UpdatePlayerProgressionParams struct {
	Level              int64 `json:"level"`
	Experience         int64 `json:"experience"`
	PrestigeLevel      int64 `json:"prestige_level"`
	DataCurrency       int64 `json:"data_currency"`
	TotalMatchesPlayed int64 `json:"total_matches_played"`
	TotalWavesSurvived int64 `json:"total_waves_survived"`
	TotalKills         int64 `json:"total_kills"`
	TotalDeaths        int64 `json:"total_deaths"`
	TotalScrapEarned   int64 `json:"total_scrap_earned"`
	TotalDataEarned    int64 `json:"total_data_earned"`
	PlayerID           int64 `json:"player_id"`
}

func (q *Queries) UpdatePlayerProgression(ctx context.Context, db DBTX, arg *UpdatePlayerProgressionParams) error {
	_, err := db.ExecContext(ctx, updatePlayerProgression,
		arg.Level,
		arg.Experience,
		arg.PrestigeLevel,
		arg.DataCurrency,
		arg.TotalMatchesPlayed,
		arg.TotalWavesSurvived,
		arg.TotalKills,
		arg.TotalDeaths,
		arg.TotalScrapEarned,
		arg.TotalDataEarned,
		arg.PlayerID,
	)
	return err
}
