// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match_stats.sql

package db

import (
	"context"
)

const createPlayerMatchStats = `-- name: CreatePlayerMatchStats :one
INSERT INTO player_match_stats (
    player_id,
    match_id,
    waves_survived,
    zombies_killed,
    deaths,
    scrap_earned,
    data_earned,
    damage_dealt,
    damage_taken,
    buildings_built,
    buildings_destroyed,
    healing_given,
    revives,
    score
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING player_id, match_id, waves_survived, zombies_killed, deaths, scrap_earned, data_earned, damage_dealt, damage_taken, buildings_built, buildings_destroyed, healing_given, revives, score
`

type CreatePlayerMatchStatsParams struct {
	PlayerID           int64 `json:"player_id"`
	MatchID            int64 `json:"match_id"`
	WavesSurvived      int64 `json:"waves_survived"`
	ZombiesKilled      int64 `json:"zombies_killed"`
	Deaths             int64 `json:"deaths"`
	ScrapEarned        int64 `json:"scrap_earned"`
	DataEarned         int64 `json:"data_earned"`
	DamageDealt        int64 `json:"damage_dealt"`
	DamageTaken        int64 `json:"damage_taken"`
	BuildingsBuilt     int64 `json:"buildings_built"`
	BuildingsDestroyed int64 `json:"buildings_destroyed"`
	HealingGiven       int64 `json:"healing_given"`
	Revives            int64 `json:"revives"`
	Score              int64 `json:"score"`
}

func (q *Queries) CreatePlayerMatchStats(ctx context.Context, db DBTX, arg *CreatePlayerMatchStatsParams) (*PlayerMatchStat, error) {
	row := db.QueryRowContext(ctx, createPlayerMatchStats,
		arg.PlayerID,
		arg.MatchID,
		arg.WavesSurvived,
		arg.ZombiesKilled,
		arg.Deaths,
		arg.ScrapEarned,
		arg.DataEarned,
		arg.DamageDealt,
		arg.DamageTaken,
		arg.BuildingsBuilt,
		arg.BuildingsDestroyed,
		arg.HealingGiven,
		arg.Revives,
		arg.Score,
	)
	var i PlayerMatchStat
	err := row.Scan(
		&i.PlayerID,
		&i.MatchID,
		&i.WavesSurvived,
		&i.ZombiesKilled,
		&i.Deaths,
		&i.ScrapEarned,
		&i.DataEarned,
		&i.DamageDealt,
		&i.DamageTaken,
		&i.BuildingsBuilt,
		&i.BuildingsDestroyed,
		&i.HealingGiven,
		&i.Revives,
		&i.Score,
	)
	return &i, err
}

const getMatchPlayerStats = `-- name: GetMatchPlayerStats :many
SELECT player_id, match_id, waves_survived, zombies_killed, deaths, scrap_earned, data_earned, damage_dealt, damage_taken, buildings_built, buildings_destroyed, healing_given, revives, score FROM player_match_stats 
WHERE match_id = ?
`

func (q *Queries) GetMatchPlayerStats(ctx context.Context, db DBTX, matchID int64) ([]*PlayerMatchStat, error) {
	rows, err := db.QueryContext(ctx, getMatchPlayerStats, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PlayerMatchStat{}
	for rows.Next() {
		var i PlayerMatchStat
		if err := rows.Scan(
			&i.PlayerID,
			&i.MatchID,
			&i.WavesSurvived,
			&i.ZombiesKilled,
			&i.Deaths,
			&i.ScrapEarned,
			&i.DataEarned,
			&i.DamageDealt,
			&i.DamageTaken,
			&i.BuildingsBuilt,
			&i.BuildingsDestroyed,
			&i.HealingGiven,
			&i.Revives,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerMatchStats = `-- name: GetPlayerMatchStats :one
SELECT player_id, match_id, waves_survived, zombies_killed, deaths, scrap_earned, data_earned, damage_dealt, damage_taken, buildings_built, buildings_destroyed, healing_given, revives, score FROM player_match_stats 
WHERE player_id = ? AND match_id = ?
`

type GetPlayerMatchStatsParams struct {
	PlayerID int64 `json:"player_id"`
	MatchID  int64 `json:"match_id"`
}

func (q *Queries) GetPlayerMatchStats(ctx context.Context, db DBTX, arg *GetPlayerMatchStatsParams) (*PlayerMatchStat, error) {
	row := db.QueryRowContext(ctx, getPlayerMatchStats, arg.PlayerID, arg.MatchID)
	var i PlayerMatchStat
	err := row.Scan(
		&i.PlayerID,
		&i.MatchID,
		&i.WavesSurvived,
		&i.ZombiesKilled,
		&i.Deaths,
		&i.ScrapEarned,
		&i.DataEarned,
		&i.DamageDealt,
		&i.DamageTaken,
		&i.BuildingsBuilt,
		&i.BuildingsDestroyed,
		&i.HealingGiven,
		&i.Revives,
		&i.Score,
	)
	return &i, err
}
