// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: join_tokens.sql

package db

import (
	"context"

	"ai-zombie-defense/backend-api/db/types"
)

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO join_tokens (
    token,
    player_id,
    server_id,
    expires_at
) VALUES (?, ?, ?, ?)
RETURNING join_token_id, token, player_id, server_id, expires_at, created_at, used_at
`

type CreateJoinTokenParams struct {
	Token     string          `json:"token"`
	PlayerID  int64           `json:"player_id"`
	ServerID  int64           `json:"server_id"`
	ExpiresAt types.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateJoinToken(ctx context.Context, db DBTX, arg *CreateJoinTokenParams) (*JoinToken, error) {
	row := db.QueryRowContext(ctx, createJoinToken,
		arg.Token,
		arg.PlayerID,
		arg.ServerID,
		arg.ExpiresAt,
	)
	var i JoinToken
	err := row.Scan(
		&i.JoinTokenID,
		&i.Token,
		&i.PlayerID,
		&i.ServerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM join_tokens
WHERE expires_at <= strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
   OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const getJoinToken = `-- name: GetJoinToken :one
SELECT join_token_id, token, player_id, server_id, expires_at, created_at, used_at FROM join_tokens WHERE token = ?
`

func (q *Queries) GetJoinToken(ctx context.Context, db DBTX, token string) (*JoinToken, error) {
	row := db.QueryRowContext(ctx, getJoinToken, token)
	var i JoinToken
	err := row.Scan(
		&i.JoinTokenID,
		&i.Token,
		&i.PlayerID,
		&i.ServerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const getValidJoinToken = `-- name: GetValidJoinToken :one
SELECT join_token_id, token, player_id, server_id, expires_at, created_at, used_at FROM join_tokens
WHERE token = ?
  AND expires_at > strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
  AND used_at IS NULL
`

func (q *Queries) GetValidJoinToken(ctx context.Context, db DBTX, token string) (*JoinToken, error) {
	row := db.QueryRowContext(ctx, getValidJoinToken, token)
	var i JoinToken
	err := row.Scan(
		&i.JoinTokenID,
		&i.Token,
		&i.PlayerID,
		&i.ServerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE join_tokens
SET used_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE token = ?
`

func (q *Queries) MarkTokenUsed(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, markTokenUsed, token)
	return err
}
