// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loot_tables.sql

package db

import (
	"context"
)

const createLootTable = `-- name: CreateLootTable :one
INSERT INTO loot_tables (name, description, drop_chance, is_active)
VALUES (?, ?, ?, ?)
RETURNING loot_table_id, name, description, drop_chance, is_active, created_at
`

type CreateLootTableParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	DropChance  float64 `json:"drop_chance"`
	IsActive    int64   `json:"is_active"`
}

func (q *Queries) CreateLootTable(ctx context.Context, db DBTX, arg *CreateLootTableParams) (*LootTable, error) {
	row := db.QueryRowContext(ctx, createLootTable,
		arg.Name,
		arg.Description,
		arg.DropChance,
		arg.IsActive,
	)
	var i LootTable
	err := row.Scan(
		&i.LootTableID,
		&i.Name,
		&i.Description,
		&i.DropChance,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteLootTable = `-- name: DeleteLootTable :exec
DELETE FROM loot_tables
WHERE loot_table_id = ?
`

func (q *Queries) DeleteLootTable(ctx context.Context, db DBTX, lootTableID int64) error {
	_, err := db.ExecContext(ctx, deleteLootTable, lootTableID)
	return err
}

const getLootTable = `-- name: GetLootTable :one
SELECT loot_table_id, name, description, drop_chance, is_active, created_at FROM loot_tables
WHERE loot_table_id = ?
`

func (q *Queries) GetLootTable(ctx context.Context, db DBTX, lootTableID int64) (*LootTable, error) {
	row := db.QueryRowContext(ctx, getLootTable, lootTableID)
	var i LootTable
	err := row.Scan(
		&i.LootTableID,
		&i.Name,
		&i.Description,
		&i.DropChance,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const listActiveLootTables = `-- name: ListActiveLootTables :many
SELECT loot_table_id, name, description, drop_chance, is_active, created_at FROM loot_tables
WHERE is_active = 1
ORDER BY loot_table_id
`

func (q *Queries) ListActiveLootTables(ctx context.Context, db DBTX) ([]*LootTable, error) {
	rows, err := db.QueryContext(ctx, listActiveLootTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LootTable{}
	for rows.Next() {
		var i LootTable
		if err := rows.Scan(
			&i.LootTableID,
			&i.Name,
			&i.Description,
			&i.DropChance,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLootTables = `-- name: ListLootTables :many
SELECT loot_table_id, name, description, drop_chance, is_active, created_at FROM loot_tables
ORDER BY loot_table_id
`

func (q *Queries) ListLootTables(ctx context.Context, db DBTX) ([]*LootTable, error) {
	rows, err := db.QueryContext(ctx, listLootTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LootTable{}
	for rows.Next() {
		var i LootTable
		if err := rows.Scan(
			&i.LootTableID,
			&i.Name,
			&i.Description,
			&i.DropChance,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLootTable = `-- name: UpdateLootTable :exec
UPDATE loot_tables
SET name = ?, description = ?, drop_chance = ?, is_active = ?
WHERE loot_table_id = ?
`

type UpdateLootTableParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	DropChance  float64 `json:"drop_chance"`
	IsActive    int64   `json:"is_active"`
	LootTableID int64   `json:"loot_table_id"`
}

func (q *Queries) UpdateLootTable(ctx context.Context, db DBTX, arg *UpdateLootTableParams) error {
	_, err := db.ExecContext(ctx, updateLootTable,
		arg.Name,
		arg.Description,
		arg.DropChance,
		arg.IsActive,
		arg.LootTableID,
	)
	return err
}
