// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"ai-zombie-defense/db/types"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (player_id, token, expires_at, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	PlayerID  int64           `json:"player_id"`
	Token     string          `json:"token"`
	ExpiresAt types.Timestamp `json:"expires_at"`
	IpAddress *string         `json:"ip_address"`
	UserAgent *string         `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, db DBTX, arg *CreateSessionParams) error {
	_, err := db.ExecContext(ctx, createSession,
		arg.PlayerID,
		arg.Token,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, db DBTX, expiresAt types.Timestamp) error {
	_, err := db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByPlayer = `-- name: DeleteSessionsByPlayer :exec
DELETE FROM sessions WHERE player_id = ?
`

func (q *Queries) DeleteSessionsByPlayer(ctx context.Context, db DBTX, playerID int64) error {
	_, err := db.ExecContext(ctx, deleteSessionsByPlayer, playerID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT session_id, player_id, token, expires_at, created_at, ip_address, user_agent FROM sessions WHERE token = ?
`

func (q *Queries) GetSessionByToken(ctx context.Context, db DBTX, token string) (*Session, error) {
	row := db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.PlayerID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return &i, err
}
